name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: Build CSharp code
      run: dotnet build

    - name: Run CSharp tests
      run: dotnet test
    
    - name: Build Typescript code
      working-directory: ./DotnetTemplate.Web
      run: npm install && npm run buil

    - name: Lint Typescript code
      working-directory: ./DotnetTemplate.Web
      run: npm run lint

    - name: Test Typescript code
      working-directory: ./DotnetTemplate.Web
      run: npm t
    
    - name: Send slack response on cancellation
      uses: fjogeleit/http-request-action@v1
      if: ${{ job.status == 'cancelled'}}
      with:
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        method: 'POST'
        data: '{"text": "Action Cancelled"}'

    - name: Send slack response on success
      uses: fjogeleit/http-request-action@v1
      if: ${{ job.status == 'success'}}
      with:
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        method: 'POST'
        data: '{"text": "Action Succeeded"}'

    - name: Send slack response on failure
      uses: fjogeleit/http-request-action@v1
      if: ${{ job.status == 'failure'}}
      with:
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        method: 'POST'
        data: '{"text": "Action Failed"}'